name: Malik Daniyal
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  al-job:
    runs-on: ubuntu_latest
    steps:
      - name: Welcome steps 
        run: echo "Welcome to gitub actions"
      - name: Checkout repository
        run: actions/checkout@v4
      - name: Repository Information
        run: |
         echo "Repository name: ${{gitub.repository}}"
         echo "Type of event: ${{github.event_name}}"
         git --version
         git branch 
         git log
         

     